name: credential_manager_ios
description: iOS implementation of the credential_manager plugin using Keychain and Autofill.
version: 2.0.5
homepage: https://github.com/Djsmk123/flutter_credential_manager_compose
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  credential_manager_platform_interface:
    path: ../credential_manager_platform_interface
  plugin_platform_interface: ^2.0.2
  cbor: ^6.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: CredentialManagerPlugin
        podspecPath: ios/credential_manager_ios.podspec

