name: credential_manager_android
description: Android implementation of the credential_manager plugin using Jetpack Credential Manager API.
version: 2.0.7
homepage: https://djsmk123.github.io/flutter_credential_manager_compose
repository: https://github.com/Djsmk123/flutter_credential_manager_compose
publish_to: pub.dev
environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  credential_manager_platform_interface: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.smkwinner.cred_manager.credential_manager
        pluginClass: CredentialManagerPlugin

